console.log("Test started");

try {
  console.log(result);
} catch (error) {
  console.error("An error occurred: ", error);
  // console.log("An error occurred: ", error);
}

console.log("Test completed");
